language: python
python:
    - "2.7"
    - "3.3"
install:
    - pip install -r requirements/requirements.txt
    - git clone https://github.com/yawd/yawd-admin
    - (cd yawd-admin; python setup.py install)
    - (cd ../pyfreebilling; python manage.py syncdb)
    - python manage.py migrate
after_success:
  # Report coverage results to coveralls.io
  - pip install coveralls
  - coveralls